[workspace]
resolver = "2"
members = [
    "poem-proc-macro",
    "poem-grants",
]

[workspace.package]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
categories = ["authentication"]
homepage = "https://github.com/DDtKey/protected-endpoints"
repository = "https://github.com/DDtKey/protected-endpoints"
authors = ["DDtKey <ddttkey@gmail.com>"]

[workspace.dependencies]
poem-grants = { path = "poem-grants", version = "1.0.0-beta.3" }
poem-grants-proc-macro = { path = "poem-proc-macro", version = "1.0.0-beta.3" }
